### ISSUE TITLE
Release RAM memory consuption

### ISSUE THREAD

**Issue by samuelcarreira** [WPFerg/MusicVisualisation#1]
Hi, first of all, congrats for your work... very instructive!
I am trying to use your code to learn more about Web Audio API, and I notice a problem with the song loading process.
After a few songs, the memory consumption increases at abnormal levels (like hundreds of MB). I think it's because of the previous file still in memory. See the pic:

![capturar](https://cloud.githubusercontent.com/assets/4456690/25977859/7be5f1e0-36b6-11e7-98f6-5692d6a3fe58.PNG)

Do you have any suggestions to manage this issue?

**Comment by WPFerg** [comment]
Hi - thanks for the feedback!

I'm not 100% sure what the problem is, though it could be the following:

* Memory is still allocated to the file (though I believe it's streamed in from the hard drive and deallocated after it's finished playing, along with any event handlers, etc)
* It may be that I haven't implemented canvas correctly and there's still some loose references lying around between frame draws. (The SVG solution was a lot worse for this as it caused frequent freezes every 60s or so). Following on from this the page background colour still changes every frame draw via the DOM so this could be causing it.
* File searching may not be implemented memory efficiently.

I'll try and get a look when I have some free time :)

**Comment by samuelcarreira** [comment]
Hi, I notice that the problem is related to web audio API file loading and not with the visualization code. I ran some tests with only a simple audio tag and the RAM consumption increases at each song.
After some research I found that many people complaint about the gargage colector on Node / V8 engine. This engine is well know for allocate a lot of the free RAM on simple tasks (even without memory leaks).
Also, I notice that the use of "use strict" directive "helps" on memory management (after I used that directive I notice a decrease on the memory consumption)
I think that you can close this issue....
Thank you very much for your help ;-)
